apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: set.frank.elsinga.de
    namespace: toptool
spec:
    commonName: set.frank.elsinga.de
    dnsNames:
        - set.frank.elsinga.de
    secretName: set.frank.elsinga.de
    issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
