apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: toptool-mediafiles-pvc
  namespace: toptool
  labels:
    app: toptool
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
