apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: top.frank.elsinga.de
  namespace: toptool
spec:
  commonName: top.frank.elsinga.de
  dnsNames:
    - top.frank.elsinga.de
  secretName: top.frank.elsinga.de
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
