# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardtop',
            name='protokoll_templ',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='top',
            name='protokoll_templ',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardtop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='top',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
