# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0002_auto_20160302_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardtop',
            name='description',
            field=models.TextField(blank=True, verbose_name='Kurze Beschreibung'),
        ),
        migrations.AlterField(
            model_name='standardtop',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe'),
        ),
        migrations.AlterField(
            model_name='standardtop',
            name='protokoll_templ',
            field=models.TextField(blank=True, verbose_name='Protokoll-Template'),
        ),
        migrations.AlterField(
            model_name='standardtop',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel des TOPs'),
        ),
        migrations.AlterField(
            model_name='standardtop',
            name='topid',
            field=models.IntegerField(verbose_name='TOP-Id'),
        ),
        migrations.AlterField(
            model_name='top',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Dein Name'),
        ),
        migrations.AlterField(
            model_name='top',
            name='description',
            field=models.TextField(blank=True, verbose_name='Kurze Beschreibung'),
        ),
        migrations.AlterField(
            model_name='top',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Deine E-Mailadresse'),
        ),
        migrations.AlterField(
            model_name='top',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting', verbose_name='Sitzung'),
        ),
        migrations.AlterField(
            model_name='top',
            name='protokoll_templ',
            field=models.TextField(blank=True, verbose_name='Protokoll-Template'),
        ),
        migrations.AlterField(
            model_name='top',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeit'),
        ),
        migrations.AlterField(
            model_name='top',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel des TOPs'),
        ),
        migrations.AlterField(
            model_name='top',
            name='topid',
            field=models.IntegerField(verbose_name='TOP-Id'),
        ),
    ]
