# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0003_auto_20160305_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top',
            name='time',
        ),
    ]
