# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models

import tops.models


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0004_top_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tops.models.attachment_path, validators=[tops.models.validate_file_type], verbose_name='Anhang'),
        ),
    ]
