# Generated by Django 1.11.2 on 2017-10-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models

import tops.models
import toptool.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("tops", "0005_auto_20170920_1204"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=tops.models.AttachmentStorage(),
                upload_to=tops.models.attachment_path,
                validators=[toptool.utils.files.validate_file_type],
                verbose_name="Anhang",
            ),
        ),
    ]
