# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tops', '0006_auto_20171001_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
