# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models

import tops.models
import toptool.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ("tops", "0007_top_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Erlaubte Dateiformate: pdf, ods, xlsx",
                null=True,
                storage=tops.models.AttachmentStorage(),
                upload_to=tops.models.attachment_path,
                validators=[toptool.shortcuts.validate_file_type],
                verbose_name="Anhang",
            ),
        ),
    ]
