# Generated by Django 3.2.9 on 2021-12-09 20:33

from django.db import migrations, models
import tops.models
import toptool.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0008_auto_20180722_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top',
            name='attachment',
            field=models.FileField(blank=True, help_text='Erlaubte Dateiformate: pdf, ods, xlsx, png, jpg, jpeg', null=True, storage=tops.models.AttachmentStorage(), upload_to=tops.models.attachment_path, validators=[toptool.utils.files.validate_file_type], verbose_name='Anhang'),
        ),
    ]
