# Generated by Django 4.0 on 2021-12-31 17:32

from django.db import migrations, models

import tops.models
import toptool.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("tops", "0009_alter_top_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Erlaubte Dateiformate: %(filetypes)s",
                null=True,
                storage=tops.models.AttachmentStorage(),
                upload_to=tops.models.attachment_path,
                validators=[toptool.utils.files.validate_file_type],
                verbose_name="Anhang",
            ),
        ),
    ]
