# Generated by Django 4.1.5 on 2023-01-15 23:09

from django.db import migrations, models

import tops.models
import toptool.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("tops", "0010_alter_top_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="top",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Erlaubte Dateiformate: pdf, ods, xlsx, png, jpg, jpeg",
                null=True,
                storage=tops.models.AttachmentStorage(),
                upload_to=tops.models.attachment_path,
                validators=[toptool.utils.files.validate_file_type],
                verbose_name="Anhang",
            ),
        ),
    ]
