# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('room', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('topdeadline', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='attendees', to='persons.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=20)),
                ('mailinglist', models.CharField(max_length=50)),
                ('approve', models.BooleanField()),
                ('attendance', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.MeetingType'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='protokollant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protokollant', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sitzungsleitung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitzungsleitung', to='persons.Person'),
        ),
    ]
