# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('meetingtypes', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='protokollant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='protokollant', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sitzungsleitung',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitzungsleitung', to='persons.Person'),
        ),
    ]
