# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20160306_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Importierte Sitzung'),
        ),
    ]
