# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20160301_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='topdeadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
