# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20160301_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='protokollant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protokollant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sitzungsleitung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitzungsleitung', to=settings.AUTH_USER_MODEL),
        ),
    ]
