# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20160301_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
    ]
