# Generated by Django 2.2.14 on 2020-07-10 17:06

from django.db import migrations


def migrate_minute_takers(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')

    for meeting in Meeting.objects.all():
        meeting.minute_takers.add(meeting.protokollant)


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20200710_1905'),
    ]
    

    operations = [
        migrations.RunPython(migrate_minute_takers),
    ]
