# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_remove_meeting_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='semester',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='protokollant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protokollant', to=settings.AUTH_USER_MODEL, verbose_name='Protokollant/in'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='room',
            field=models.CharField(blank=True, max_length=200, verbose_name='Raum'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sitzungsleitung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitzungsleitung', to=settings.AUTH_USER_MODEL, verbose_name='Sitzungsleitung'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(verbose_name='Zeit'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alternativer Titel'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='topdeadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='TOP-Einreichungsfrist'),
        ),
    ]
