# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20160305_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='stdtops_created',
            field=models.BooleanField(default=False, verbose_name='Standard-TOPs wurden eingetragen'),
        ),
    ]
