# Generated by Django 2.2.14 on 2020-07-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0008_auto_20200710_1906"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="protokollant",
        ),
    ]
