# Generated by Django 3.2.8 on 2021-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0009_remove_meeting_protokollant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="topdeadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Frist, bis zu der TOPs eingereicht werden können. "
                "Wenn keine Frist gesetzt ist, können bis zum Beginn der Sitzung TOPs eingetragen werden. ",
                null=True,
                verbose_name="TOP-Einreichungsfrist",
            ),
        ),
    ]
