# Generated by Django 4.0 on 2021-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0010_alter_meeting_topdeadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="topdeadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Frist, bis zu der TOPs eingereicht werden können. "
                "Wenn keine Frist gesetzt ist, können bis zum Beginn der Sitzung TOPs eingetragen werden.",
                null=True,
                verbose_name="TOP-Einreichungsfrist",
            ),
        ),
    ]
