# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('protokolle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protokoll',
            old_name='time',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='protokoll',
            name='id',
        ),
        migrations.AddField(
            model_name='protokoll',
            name='begin',
            field=models.TimeField(default=datetime.datetime(2016, 3, 4, 20, 23, 42, 354348, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protokoll',
            name='end',
            field=models.TimeField(default=datetime.datetime(2016, 3, 4, 20, 23, 53, 322317, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meetings.Meeting'),
        ),
    ]
