# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import protokolle.models


class Migration(migrations.Migration):

    dependencies = [
        ('protokolle', '0002_auto_20160304_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='html',
            field=models.FileField(null=True, upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='pdf',
            field=models.FileField(null=True, upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='t2t',
            field=models.FileField(null=True, upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='tex',
            field=models.FileField(null=True, upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AddField(
            model_name='protokoll',
            name='txt',
            field=models.FileField(null=True, upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='version',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
