# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import protokolle.models


class Migration(migrations.Migration):

    dependencies = [
        ('protokolle', '0003_auto_20160304_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protokoll',
            name='html',
            field=models.FileField(upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='pdf',
            field=models.FileField(upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='t2t',
            field=models.FileField(upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='tex',
            field=models.FileField(upload_to=protokolle.models.protokoll_path),
        ),
        migrations.AlterField(
            model_name='protokoll',
            name='txt',
            field=models.FileField(upload_to=protokolle.models.protokoll_path),
        ),
    ]
