# Generated by Django 2.0.7 on 2018-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protokolle', '0006_auto_20180722_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='protokoll',
            name='published',
            field=models.BooleanField(default=True, verbose_name='veröffentlicht'),
            preserve_default=False,
        ),
    ]
