# Generated by Django 4.0 on 2021-12-31 17:51

from django.db import migrations, models

import protokolle.models
import toptool.utils.files


class Migration(migrations.Migration):

    dependencies = [
        ("protokolle", "0008_alter_attachment_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment",
            field=models.FileField(
                help_text="Erlaubte Dateiformate: %(filetypes)s",
                storage=protokolle.models.AttachmentStorage(),
                upload_to=protokolle.models.attachment_path,
                validators=[toptool.utils.files.validate_file_type],
                verbose_name="Anhang",
            ),
        ),
    ]
