# Generated by Django 1.11 on 2018-01-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_auto_20180128_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(blank=True, max_length=30, verbose_name="Farbe"),
        ),
    ]
