# Generated by Django 1.11 on 2018-02-10 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetingtypes", "0006_auto_20180210_1122"),
        ("userprofile", "0005_meetingtypepreference"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingtypepreference",
            unique_together={("user", "meetingtype")},
        ),
    ]
