# Generated by Django 2.0.7 on 2018-11-06 08:16

import uuid

from django.db import migrations


def gen_ical_keys(apps, schema_editor):
    Profile = apps.get_model("userprofile", "Profile")
    for profile in Profile.objects.all():
        profile.ical_key = uuid.uuid4()
        profile.save(update_fields=["ical_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_profile_ical_key"),
    ]

    operations = [
        migrations.RunPython(gen_ical_keys),
    ]
