# Generated by Django 2.0.7 on 2018-11-06 08:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_change_ical_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ical_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                verbose_name="iCal-Key",
            ),
        ),
    ]
