# Generated by Django 4.0 on 2021-12-21 20:29

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Profile = apps.get_model("userprofile", "Profile")
    db_alias = schema_editor.connection.alias
    for profile in Profile.objects.using(db_alias).all():
        profile.colormode.replace("default", "light")
        profile.color.replace("black", "#000000")
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0011_alter_profile_colormode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="colormode",
            field=models.CharField(
                blank=True,
                choices=[("light", "Hell"), ("dark", "Dunkel")],
                default="light",
                max_length=30,
                verbose_name="Farbschema",
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
