# Generated by Django 4.0 on 2021-12-21 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0012_alter_profile_colormode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator("^#[0-9a-fA-F]{6}$", "Nur valide Hex-Farbcodes sind erlaubt"),
                ],
                verbose_name="Farbe",
            ),
        ),
    ]
