# Generated by Django 4.0 on 2021-12-25 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_alter_profile_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color",
            field=models.CharField(
                default="#337ab7",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator("^#[0-9a-fA-F]{6}$", "Nur valide Hex-Farbcodes sind erlaubt"),
                ],
                verbose_name="Farbe",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="colormode",
            field=models.CharField(
                choices=[("light", "Hell"), ("dark", "Dunkel")],
                default="light",
                max_length=30,
                verbose_name="Farbschema",
            ),
        ),
    ]
