# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetingtypes', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('version', models.DateTimeField(verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Amt')),
                ('plural', models.CharField(blank=True, max_length=200, verbose_name='Amt im Plural')),
                ('meetingtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('version', models.DateTimeField(auto_now=True, verbose_name='Version')),
                ('functions', models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Aemter')),
                ('meetingtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe')),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Aemter'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting', verbose_name='Sitzung'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Person', verbose_name='Person'),
        ),
    ]
