# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function'),
        ),
    ]
