# Generated by Django 1.9 on 2016-08-23 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="sort_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Name für Sortierung",
            ),
        ),
    ]
