# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20160306_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
