# Generated by Django 1.11.2 on 2017-09-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_function_sort_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="sort_name",
        ),
        migrations.AddField(
            model_name="function",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Index für Sortierung"),
            preserve_default=False,
        ),
    ]
