# Generated by Django 3.2.8 on 2021-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_auto_20170909_2115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="functions",
            field=models.ManyToManyField(blank=True, to="persons.Function", verbose_name="Ämter"),
        ),
        migrations.AlterField(
            model_name="person",
            name="functions",
            field=models.ManyToManyField(blank=True, to="persons.Function", verbose_name="Ämter"),
        ),
    ]
