# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20160303_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendant',
            new_name='Attendee',
        ),
    ]
