# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 12:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20160309_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_selected',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 12, 49, 58, 79786, tzinfo=utc), verbose_name='Zuletzt anwesend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='version',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zuletzt geändert'),
        ),
    ]
