# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0004_auto_20160302_1113'),
        ('persons', '0004_auto_20160303_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='meetingtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType'),
            preserve_default=False,
        ),
    ]
