# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20160309_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='version',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zuletzt geaendert'),
        ),
    ]
