# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_person_meetingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
