# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20160303_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
