# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_function_meetingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Ämter'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting', verbose_name='Sitzung'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='version',
            field=models.DateTimeField(verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='function',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Amt'),
        ),
        migrations.AlterField(
            model_name='function',
            name='plural',
            field=models.CharField(blank=True, max_length=200, verbose_name='Amt im Plural'),
        ),
        migrations.AlterField(
            model_name='person',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Ämter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='meetingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingtypes.MeetingType', verbose_name='Sitzungsgruppe'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='version',
            field=models.DateTimeField(auto_now=True, verbose_name='Version'),
        ),
    ]
