# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20160305_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Aemter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='functions',
            field=models.ManyToManyField(blank=True, to='persons.Function', verbose_name='Aemter'),
        ),
    ]
