# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=20, unique=True)),
                ('mailinglist', models.CharField(max_length=50)),
                ('approve', models.BooleanField()),
                ('attendance', models.BooleanField()),
                ('admin_permission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission', to='auth.Permission')),
                ('permission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='auth.Permission')),
            ],
        ),
    ]
