# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtype',
            name='admin_permission',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='permission',
            field=models.CharField(max_length=200),
        ),
    ]
