# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0002_auto_20160301_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
