# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0003_meetingtype_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtype',
            name='admin_permission',
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='permission',
        ),
    ]
