# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0003_meetingtype_first_topid"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="attachment_tops",
            field=models.BooleanField(default=False, verbose_name="Anhänge zu TOPs"),
            preserve_default=False,
        ),
    ]
