# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0004_auto_20160302_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='attendance_with_func',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
