# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0005_meetingtype_attendance_with_func'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='other_in_tops',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
