# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0005_meetingtype_attachment_protokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtype',
            name='pad_setting',
            field=models.BooleanField(default=False, verbose_name='Protokoll auch online schreiben (mit Etherpad)'),
            preserve_default=False,
        ),
    ]
