# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0006_meetingtype_other_in_tops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtype',
            name='approve',
            field=models.BooleanField(verbose_name='Protokolle müssen genehmigt werden'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='attendance',
            field=models.BooleanField(verbose_name='Anwesenheitsliste'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='attendance_with_func',
            field=models.BooleanField(verbose_name='Anwesenheitslist mit Ämtern'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='mailinglist',
            field=models.CharField(max_length=50, verbose_name='Mailingliste'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='other_in_tops',
            field=models.BooleanField(verbose_name='TOP "Sonstiges" standardmäßig hinzufügen'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='public',
            field=models.BooleanField(verbose_name='Sitzungsgruppe ist öffentlich'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='shortname',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kurzname'),
        ),
    ]
