# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0007_auto_20160305_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtype',
            name='approve',
            field=models.BooleanField(verbose_name='Protokolle muessen genehmigt werden'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='attendance_with_func',
            field=models.BooleanField(verbose_name='Anwesenheitslist mit Aemtern'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='other_in_tops',
            field=models.BooleanField(verbose_name='TOP "Sonstiges" standardmaessig hinzufuegen'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='public',
            field=models.BooleanField(verbose_name='Sitzungsgruppe ist oeffentlich'),
        ),
    ]
