# Generated by Django 1.11 on 2018-02-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0010_meetingtype_write_protokoll_button"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="standard_tops",
            field=models.BooleanField(
                default=True,
                verbose_name="Standard-TOPs (TOPs, die für jede Sitzung automatisch erstellt werden) verwenden",
            ),
            preserve_default=False,
        ),
    ]
