# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0014_auto_20180212_1821"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="top_user_edit",
            field=models.BooleanField(
                default=False,
                verbose_name="Benutzer dürfen ihre eigenen TOPs bearbeiten/löschen",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meetingtype",
            name="top_perms",
            field=models.CharField(
                choices=[
                    (
                        "admin",
                        "Nur Sitzungsgruppen-Admins und Sitzungsleitung können TOPs eintragen",
                    ),
                    (
                        "perm",
                        "Nur Benutzer mit Rechten für die Sitzungsgruppen können TOPs eintragen",
                    ),
                    (
                        "public",
                        "Alle, auch nicht eingeloggte Benutzer, können TOPs eintragen "
                        "(nur relevant, wenn Sitzungsgruppe öffentlich ist)",
                    ),
                ],
                default="public",
                max_length=10,
                verbose_name="Rechte für das Eintragen von TOPs",
            ),
        ),
    ]
