# Generated by Django 1.11 on 2018-03-22 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0015_auto_20180218_1052"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingtype",
            name="pad_setting",
            field=models.BooleanField(
                default=False,
                verbose_name="Protokoll auch online schreiben (mit Etherpad)",
            ),
            preserve_default=False,
        ),
    ]
