# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingtypes', '0015_auto_20180218_1052'),
        ('meetingtypes', '0006_meetingtype_pad_setting'),
    ]

    operations = [
    ]
