# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0019_auto_20180723_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtype",
            name="approve",
            field=models.BooleanField(
                verbose_name="Protokolle müssen genehmigt werden, bevor sie veröffentlicht werden",
            ),
        ),
    ]
