# Generated by Django 2.2.12 on 2020-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0020_auto_20180723_1127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtype",
            name="mailinglist",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Mailingliste",
            ),
        ),
    ]
