# Generated by Django 4.0 on 2021-12-31 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetingtypes", "0023_auto_20200710_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingtype",
            name="id",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator("^[a-z]+$", "Nur Buchstaben von a-z erlaubt!"),
                    django.core.validators.RegexValidator(
                        "^(admin|i18n|profile|meeting|meeting|protokoll|person|meetingtype|list|overview|"
                        "static|media|login|logout|oidc)$",
                        "Name ist reserviert!",
                        inverse_match=True,
                    ),
                    django.core.validators.MinLengthValidator(
                        2,
                        "Der URL-Kurzname muss mindestens 2 Buchstaben enthalten.",
                    ),
                ],
                verbose_name="URL-Kurzname",
            ),
        ),
    ]
