name: Syncs this repo with the one hosted on private gitlab

on:
  push:
    branches:
      - 'main'
      - 'dev'
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'FSTUM/toptool-v3'
          source_branch: 'main'
          destination_repo: 'git@git.fs.tum.de:fsmpi/toptool.git'
          destination_branch: 'master'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'FSTUM/toptool-v3'
          source_branch: 'dev'
          destination_repo: 'git@git.fs.tum.de:fsmpi/toptool.git'
          destination_branch: 'dev'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
